#version 430 core

// We don't use any 'in' attributes from a VBO for this shader.

uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;

// Input: The buffer of points generated by the compute shader
layout(std430, binding = 1) readonly buffer PointsBuffer {
    vec4 points[];
} point_buffer;

void main() {
    // Fetch the position for this vertex using its unique ID
    vec4 pos = point_buffer.points[gl_VertexID];
    
    // Standard model-view-projection transformation
    gl_Position = projection * view * model * pos;

    // Make points smaller the further they are from the camera
    float distance = length(gl_Position.xyz);
    gl_PointSize = 30.0 / distance;
}
